version: '2'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - DEBUG=on
      - DJANGO_SETTINGS_MODULE=settings.dev
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=root
      - POSTGRES_DB=app
    command: ./manage.py runserver 0.0.0.0:8080

  db:
    image: postgres:alpine
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=root
      - POSTGRES_DB=app
    volumes:
      - ./.data/db:/var/lib/postgresql/data

