# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excomment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('diff', models.TextField(max_length=511, null=True, verbose_name='Encode Differ')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'Create'), (1, 'Modification'), (2, 'Delete')])),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='excomment.Comment', verbose_name='Comment')),
                ('who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
